ssl:
  key: "localhost-key.pem"
  cert: "localhost.pem"
session:
  secret: ""
jwt:
  token: ""
db:
  host: "localhost"
  port: 3306
  user: "root"
  password: ""
  database: "tihochat"
peer:
  host: "localhost"
turn:
  secret: "long-strong-secret"
default:
  password: 'hard-to-guess-password'